name: Update Webb Status
on:
  schedule:
    - cron:  '45 * * * *'

jobs:
  update_status:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm start
      - uses: fregante/setup-git-user@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update status"